project:
  type: website
  output-dir: docs
  resources:
    - google7ddc14bf0b740639.html
website:
  title: "Malin Müller"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications and Talks
      - href: cv.qmd
        text: CV
      - href: awards.qmd
        text: Awards

    right:
      - icon: linkedin
        href: https://de.linkedin.com/in/malin-m%C3%BCller-09a419226

  page-footer:
    left: "© 2026 Malin Müller"
    center: "[Impressum & Datenschutz](impressum.qmd)"
    right: "Built with [Quarto](https://quarto.org/)"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual