---
title: "Publications and Talks"
---

## Publications

**Müller, M.**, Schmitt, M. C., Schemer, L., Basten, U., Glombiewski, J. A., Karbach, J., Könen, T., & Lischetzke, T. (2026). Careless responding in ambulatory assessment: Comparing individuals with and without chronic pain. *Psychological Assessment*. Advance online publication. DOI: <https://doi.org/10.1037/pas0001485>

## Conference Presentations

### 2026

**Müller, M.**, Maciejewski, D., Schorrlepp, L., Lischetzke, T., & Vogelsmeier, L. V. D. E. (June 24–26, 2026). Triangulating Inattentive Responding: Using Response Processes as a Qualitative Lens on Quantitative Detection Methods in ESM. *IOPS–SMiP Summer Conference 2026*, Groningen, The Netherlands.

### 2025

**Müller, M.**, Schmitt, M. C., Schemer, L., Basten, U., Glombiewski, J. A., Karbach, J., Könen, T., & Lischetzke, T. (September 29–October 1, 2025). Careless Responding in Ambulatory Assessment: Comparing Individuals with and without Chronic Pain. *Conference of the DGPs Methods and Evaluation Section 2025*, Berlin, Germany.

**Müller, M.**, Schmitt, M. C., Schemer, L., Basten, U., Glombiewski, J. A., Karbach, J., Könen, T., & Lischetzke, T. (May 26–28, 2025). Careless Responding in Ambulatory Assessment: Comparing Individuals with and without Chronic Pain. *Society for Ambulatory Assessment Conference 2025*, Leuven, Belgium.
